[package]
name = "warp_example"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = "1.4.1"
pretty_env_logger = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.210"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
